TROL A2:
  inputKind: ffmpeg_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 0
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 1440.0
    positionX: 0.0
    positionY: 0.0
    rotation: 0.0
    scaleX: 1.0
    scaleY: 1.0
    sourceHeight: 1440.0
    sourceWidth: 2560.0
    width: 2560.0
  sourceName: TROL A2
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: TROL A2
  inputSettings:
    buffering_mb: 1
    close_when_inactive: true
    ffmpeg_options: rtps_transport=tcp rtsp_flags=prefer_tcp
    hw_decode: true
    is_local_file: false
  inputMuted: false
  inputVolumeMul: 0.6302061676979065
  inputAudioSyncOffset: 0
TROL A1:
  inputKind: ffmpeg_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 1
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 1440.0
    positionX: 0.0
    positionY: 0.0
    rotation: 0.0
    scaleX: 1.0
    scaleY: 1.0
    sourceHeight: 1440.0
    sourceWidth: 2560.0
    width: 2560.0
  sourceName: TROL A1
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: TROL A1
  inputSettings:
    buffering_mb: 1
    close_when_inactive: true
    ffmpeg_options: rtps_transport=tcp rtsp_flags=prefer_tcp
    hw_decode: true
    is_local_file: false
  inputMuted: false
  inputVolumeMul: 0.6302061676979065
  inputAudioSyncOffset: 0
StaticLoop:
  inputKind: ffmpeg_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 2
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 2160.0
    positionX: 0.0
    positionY: 0.0
    rotation: 0.0
    scaleX: 2.0
    scaleY: 2.0
    sourceHeight: 1080.0
    sourceWidth: 1920.0
    width: 3840.0
  sourceName: StaticLoop
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: StaticLoop
  inputSettings:
    clear_on_media_end: false
    hw_decode: true
    local_file: /home/chris/KA/src/trol2/resources/obs/1080-static.mp4
    looping: true
  inputMuted: true
  inputVolumeMul: 0
  inputAudioSyncOffset: 0
TROL B:
  inputKind: ffmpeg_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 3
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    boundsAlignment: 0
    boundsHeight: 1080.0
    boundsType: OBS_BOUNDS_SCALE_TO_WIDTH
    boundsWidth: 3840.0
    cropBottom: 540
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 540
    height: 2160.0
    positionX: 0.0
    positionY: 1080.0
    rotation: 0.0
    scaleX: 1.0
    scaleY: 1.0
    sourceHeight: 2160.0
    sourceWidth: 3840.0
    width: 3840.0
  sourceName: TROL B
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: TROL B
  inputSettings:
    close_when_inactive: true
    ffmpeg_options: rtsp_transport=tcp rtsp_flags=prefer_tcp
    hw_decode: false
    is_local_file: false
    reconnect_delay_sec: 1
    restart_on_activate: true
  inputMuted: true
  inputVolumeMul: 0.0
  inputAudioSyncOffset: 0
TROL TL:
  inputKind: ffmpeg_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 4
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    boundsAlignment: 5
    boundsHeight: 1080.0
    boundsType: OBS_BOUNDS_SCALE_INNER
    boundsWidth: 1920.0
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 1080.0
    positionX: 0.0
    positionY: 0.0
    rotation: 0.0
    scaleX: 0.75
    scaleY: 0.75
    sourceHeight: 1440.0
    sourceWidth: 2560.0
    width: 1920.0
  sourceName: TROL TL
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: TROL TL
  inputSettings:
    close_when_inactive: true
    ffmpeg_options: rtsp_transport=tcp rtsp_flags=prefer_tcp
    hw_decode: false
    is_local_file: false
    reconnect_delay_sec: 1
    restart_on_activate: true
  inputMuted: true
  inputVolumeMul: 0.0
  inputAudioSyncOffset: 0
TROL TR:
  inputKind: ffmpeg_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 5
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    boundsAlignment: 5
    boundsHeight: 1080.0
    boundsType: OBS_BOUNDS_SCALE_INNER
    boundsWidth: 1920.0
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 1080.0
    positionX: 1920.0
    positionY: 0.0
    rotation: 0.0
    scaleX: 0.75
    scaleY: 0.75
    sourceHeight: 1440.0
    sourceWidth: 2560.0
    width: 1920.0
  sourceName: TROL TR
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: TROL TR
  inputSettings:
    close_when_inactive: true
    ffmpeg_options: rtsp_transport=tcp rtsp_flags=prefer_tcp
    hw_decode: false
    is_local_file: false
    reconnect_delay_sec: 1
    restart_on_activate: true
  inputMuted: true
  inputVolumeMul: 0.0
  inputAudioSyncOffset: 0
Border:
  inputKind: image_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 6
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 2160.0
    positionX: 0.0
    positionY: 0.0
    rotation: 0.0
    scaleX: 2.0
    scaleY: 2.0
    sourceHeight: 1080.0
    sourceWidth: 1920.0
    width: 3840.0
  sourceName: Border
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: Border
  inputSettings:
    file: /home/chris/KA/src/trol2/resources/obs/border.png
Clock:
  inputKind: browser_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 7
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 150.0
    positionX: 44.0
    positionY: 1992.0
    rotation: 0.0
    scaleX: 1.0
    scaleY: 1.0
    sourceHeight: 150.0
    sourceWidth: 1000.0
    width: 1000.0
  sourceName: Clock
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: Clock
  inputSettings:
    fps: 2
    height: 150
    is_local_file: true
    local_file: /home/chris/KA/src/trol2/obs/clock.html
    width: 1000
Scroll:
  inputKind: browser_source
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: false
  sceneItemIndex: 8
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 200.0
    positionX: 1104.0
    positionY: 1963.0
    rotation: 0.0
    scaleX: 1.0
    scaleY: 1.0
    sourceHeight: 200.0
    sourceWidth: 2700.0
    width: 2700.0
  sourceName: Scroll
  sourceType: OBS_SOURCE_TYPE_INPUT
  inputName: Scroll
  inputSettings:
    fps: 60
    height: 200
    is_local_file: true
    local_file: /home/chris/KA/src/trol2/obs/scroll/scroll.html
    restart_when_active: false
    shutdown: true
    width: 2700

