# The camera's name used throughout the system
# REQUIRED
name: "example"
# A "nice" version of the name that's used only for display to Discord users at the time of writing
# OPTIONAL
nice_name: "Annex Pineapple View"

# Address is only the DNS entry, not any path or protocol.
# REQUIRED
address: "examplecam.kitten.academy"

# You can provide a camera "type" OR you can provide the camera URLs, you don't need both
# since "type" is only used to construct URLs.  Or provide both, we'll just ignore the type.
#
# Available types are: ANPVIZ, AMCREST, LOREX, MOTO, GENERIC
# These do not necessarily correspond with anything in reality
# See initialize/cameras.py for details
type: "ANPVIZ"
# OR 
rtspurl: "rtsp://user:pass@examplecam.kitten.academy/cam/realmonitor?channel=1&subtype=0"
audiourl: "rtsp://user:pass@examplecam.kitten.academy/cam/realmonitor?channel=1&subtype=1"
jpgurl: "http://user:pass@examplecam.kitten.academy/cgi-bin/snapshot.cgi?1" 

# The following are all optional for you to provide, defaults as shown below.
#
# ispublic determines whether Discord Admins can see this camera.
ispublic: False
# ishidden detemines whether Discord Users can see this camera.
ishidden: False
# nothumb means don't expect to get regular screenshots/thumbnails from this camera
nothumb: False
# noaudio means we disallow use of this camera for audio
noaudio: False

