name: "TROL TR"
nice_name: Top Right
isaudio: true
obs_item_default:
  inputAudioSyncOffset: 0
  inputKind: ffmpeg_source
  inputMuted: true
  inputName: TROL TR
  inputSettings:
    close_when_inactive: true
    ffmpeg_options: rtsp_transport=tcp rtsp_flags=prefer_tcp
    hw_decode: false
    is_local_file: false
    reconnect_delay_sec: 1
    restart_on_activate: true
  inputVolumeMul: 0.0
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 5
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    boundsAlignment: 5
    boundsHeight: 1080.0
    boundsType: OBS_BOUNDS_SCALE_INNER
    boundsWidth: 1920.0
    cropBottom: 0
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 0
    height: 1080.0
    positionX: 1920.0
    positionY: 0.0
    rotation: 0.0
    scaleX: 0.75
    scaleY: 0.75
    sourceHeight: 1440.0
    sourceWidth: 2560.0
    width: 1920.0
  sourceName: TROL TR
  sourceType: OBS_SOURCE_TYPE_INPUT
