name: "TROL B"
nice_name: Bottom
isaudio: true
obs_item_default:
  inputAudioSyncOffset: 0
  inputKind: ffmpeg_source
  inputMuted: true
  inputName: TROL B
  inputSettings:
    close_when_inactive: true
    ffmpeg_options: rtsp_transport=tcp rtsp_flags=prefer_tcp
    hw_decode: false
    is_local_file: false
    reconnect_delay_sec: 1
    restart_on_activate: true
  inputVolumeMul: 0.0
  sceneItemBlendMode: OBS_BLEND_NORMAL
  sceneItemEnabled: true
  sceneItemIndex: 3
  sceneItemLocked: true
  sceneItemTransform:
    alignment: 5
    boundsAlignment: 0
    boundsHeight: 1080.0
    boundsType: OBS_BOUNDS_SCALE_TO_WIDTH
    boundsWidth: 3840.0
    cropBottom: 540
    cropLeft: 0
    cropRight: 0
    cropToBounds: false
    cropTop: 540
    height: 2160.0
    positionX: 0.0
    positionY: 1080.0
    rotation: 0.0
    scaleX: 1.0
    scaleY: 1.0
    sourceHeight: 2160.0
    sourceWidth: 3840.0
    width: 3840.0
  sourceName: TROL B
  sourceType: OBS_SOURCE_TYPE_INPUT

